### ISSUE TITLE
jcifs.smb.SmbException indexing files smb

### ISSUE THREAD

**Issue by Lavini281** [codelibs/fess-crawler#46]
Hi !

I tried commenting on a [closed issue](https://github.com/codelibs/fess/issues/2218) yesterday but I think it is more appropriate here.

I am having a problem crawling an SMBv2 share which contains around 1 million documents. After some hours the crawler start to fail on all the document with this error.
```
Type: jcifs.smb.SmbException

org.codelibs.fess.crawler.exception.CrawlingAccessException: Cannot get owner of the file: smb://10.0.0.1/share/12818/document_20190608.pdf at at org.codelibs.fess.crawler.client.smb.SmbClient.getResponseData(SmbClient.java:224)
at org.codelibs.fess.crawler.client.smb.SmbClient.processRequest(SmbClient.java:158)
at org.codelibs.fess.crawler.client.smb.SmbClient.doHead(SmbClient.java:390)
at org.codelibs.fess.crawler.client.AbstractCrawlerClient.execute(AbstractCrawlerClient.java:144)
at org.codelibs.fess.crawler.FessCrawlerThread.isContentUpdated(FessCrawlerThread.java:85)
at org.codelibs.fess.crawler.CrawlerThread.run(CrawlerThread.java:155)
at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: jcifs.smb.SmbException: 0xC0000128
at jcifs.smb.SmbTransportImpl.checkStatus2(SmbTransportImpl.java:1461)
at jcifs.smb.SmbTransportImpl.checkStatus(SmbTransportImpl.java:1572)
at jcifs.smb.SmbTransportImpl.sendrecv(SmbTransportImpl.java:1027)
at jcifs.smb.SmbTransportImpl.send(SmbTransportImpl.java:1543)
at jcifs.smb.SmbSessionImpl.send(SmbSessionImpl.java:409)
at jcifs.smb.SmbTreeImpl.send(SmbTreeImpl.java:472)
at jcifs.smb.SmbTreeConnection.send0(SmbTreeConnection.java:404)
at jcifs.smb.SmbTreeConnection.send(SmbTreeConnection.java:318)
at jcifs.smb.SmbTreeConnection.send(SmbTreeConnection.java:298)
at jcifs.smb.SmbTreeHandleImpl.send(SmbTreeHandleImpl.java:130)
at jcifs.smb.SmbTreeHandleImpl.send(SmbTreeHandleImpl.java:117)
at jcifs.smb.SmbFile.withOpen(SmbFile.java:1741)
at jcifs.smb.SmbFile.withOpen(SmbFile.java:1710)
at jcifs.smb.SmbFile.withOpen(SmbFile.java:1704)
at jcifs.smb.SmbFile.querySecurity(SmbFile.java:2220)
at jcifs.smb.SmbFile.getOwnerUser(SmbFile.java:2269)
at jcifs.smb.SmbFile.getOwnerUser(SmbFile.java:2262)
at org.codelibs.fess.crawler.client.smb.SmbClient.getResponseData(SmbClient.java:218)
... 6 more
```
From the microsoft [documentation](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-cifs/8f11e0f3-d545-46cc-97e6-f00569e3e1bc), it looks like it stands for "STATUS_FILE_CLOSED" but I don't have any other clue.

Each time I manually restart the crawler, it starts working again for some hours before failing again.

Crawler configuration :
* Paths : `smb://10.0.0.1/share/`
* The number of thread : `20`

Fess Version : 13.3.2

**Comment by marevol** [comment]
For smb2, we copy source code from [jcifs-ng](https://github.com/AgNO3/jcifs-ng).
So, it will have the same problem.

**Comment by Lavini281** [comment]
I just checked the logs and it is appearing after 90min each time

**Comment by Lavini281** [comment]
Sorry, it did that twice but now it is doing it after a random amount of time

**Comment by Lavini281** [comment]
As I commented on the `jcifs-ng` issue the problem was coming from the server. Thank you for your help
