### ISSUE TITLE
Can't restart crawler includes multiple WebConfigId

### ISSUE THREAD

**Issue by chizenjp** [codelibs/fess-crawler#48]
I can't restart crawler, FESS said version conflict occur in .crawler.queue index.
Errors below.

fess.log (level debug)

```
2020-01-11 22:03:54,353 [job_B56skm8B66oCPuF_MCYG] WARN  Failed to execute B56skm8B66oCPuF_MCYG: return container.getComponent("crawlJob").logLevel("debug").sessionId("BZ6rkm8B66oCPuF_NyYw").webConfigIds(["BZ6rkm8B66oCPuF_NyYw","Bp6rkm8B66oCPuF_oSYP"] as String[]).fileConfigIds([] as String[]).dataConfigIds([] as String[]).jobExecutor(executor).execute();
org.codelibs.fess.exception.JobProcessingException: Crawler Process terminated.
	at org.codelibs.fess.job.CrawlJob.executeCrawler(CrawlJob.java:374) ~[classes/:?]
	at org.codelibs.fess.job.CrawlJob.execute(CrawlJob.java:160) ~[classes/:?]
	at org.codelibs.fess.job.CrawlJob$execute.call(Unknown Source) ~[?:?]
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47) ~[groovy-3.0.0-rc-2.jar:3.0.0.rc-2]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:115) ~[groovy-3.0.0-rc-2.jar:3.0.0.rc-2]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:119) ~[groovy-3.0.0-rc-2.jar:3.0.0.rc-2]
	at Script1.run(Script1.groovy:1) ~[?:?]
	at groovy.lang.GroovyShell.evaluate(GroovyShell.java:431) ~[groovy-3.0.0-rc-2.jar:3.0.0.rc-2]
	at groovy.lang.GroovyShell.evaluate(GroovyShell.java:465) ~[groovy-3.0.0-rc-2.jar:3.0.0.rc-2]
	at groovy.lang.GroovyShell.evaluate(GroovyShell.java:440) ~[groovy-3.0.0-rc-2.jar:3.0.0.rc-2]
	at org.codelibs.fess.util.GroovyUtil.evaluate(GroovyUtil.java:42) ~[classes/:?]
	at org.codelibs.fess.job.impl.GroovyExecutor.execute(GroovyExecutor.java:31) ~[classes/:?]
	at org.codelibs.fess.app.job.ScriptExecutorJob.run(ScriptExecutorJob.java:91) [classes/:?]
	at org.lastaflute.job.LaJobRunner.actuallyRun(LaJobRunner.java:265) [lasta-job-0.5.3.jar:?]
	at org.lastaflute.job.LaJobRunner.doRun(LaJobRunner.java:232) [lasta-job-0.5.3.jar:?]
	at org.lastaflute.job.LaJobRunner.run(LaJobRunner.java:182) [lasta-job-0.5.3.jar:?]
	at org.lastaflute.job.cron4j.Cron4jTask.runJob(Cron4jTask.java:371) [lasta-job-0.5.3.jar:?]
	at org.lastaflute.job.cron4j.Cron4jTask.actuallyExecute(Cron4jTask.java:355) [lasta-job-0.5.3.jar:?]
	at org.lastaflute.job.cron4j.Cron4jTask.lambda$doExecute$6(Cron4jTask.java:258) [lasta-job-0.5.3.jar:?]
	at org.lastaflute.job.cron4j.Cron4jTask.synchronizedNeighborRunning(Cron4jTask.java:328) [lasta-job-0.5.3.jar:?]
	at org.lastaflute.job.cron4j.Cron4jTask.doExecute(Cron4jTask.java:246) [lasta-job-0.5.3.jar:?]
	at org.lastaflute.job.cron4j.Cron4jTask.execute(Cron4jTask.java:151) [lasta-job-0.5.3.jar:?]
	at it.sauronsoftware.cron4j.RomanticCron4jNativeTaskExecutor$RomanticRunner.run(RomanticCron4jNativeTaskExecutor.java:121) [lasta-job-0.5.3.jar:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.InterruptedException
	at java.lang.ProcessImpl.waitFor(ProcessImpl.java:544) ~[?:?]
	at org.codelibs.fess.job.CrawlJob.executeCrawler(CrawlJob.java:355) ~[classes/:?]
	... 23 more
```

fess crawler log (level debug)

```
2020-01-11 22:03:17,662 [eshttp] DEBUG Response in Memory
2020-01-11 22:03:17,662 [WebFsCrawler] DEBUG Failed to invoke actionGet. count:3
org.elasticsearch.ElasticsearchStatusException: Elasticsearch exception [type=version_conflict_engine_exception, reason=[BZ6rkm8B66oCPuF_NyYw-1.aHR0cHM6Ly9zaG9wLmRlbGZvbmljcy5jb20v]: version conflict, document already exists (current version [1])]
	at org.elasticsearch.rest.BytesRestResponse.errorFromXContent(BytesRestResponse.java:177) ~[elasticsearch-7.5.1.jar:7.5.1]
	at org.codelibs.elasticsearch.client.action.HttpAction.toElasticsearchException(HttpAction.java:138) ~[elasticsearch-httpclient-7.5.0.jar:?]
	at org.codelibs.elasticsearch.client.action.HttpIndexAction.lambda$execute$0(HttpIndexAction.java:58) ~[elasticsearch-httpclient-7.5.0.jar:?]
	at org.codelibs.curl.CurlRequest.lambda$execute$4(CurlRequest.java:220) ~[curl4j-1.2.4.jar:?]
	at org.codelibs.curl.CurlRequest.lambda$connect$3(CurlRequest.java:199) ~[curl4j-1.2.4.jar:?]
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177) ~[?:?]
	Suppressed: java.lang.NullPointerException
		at org.elasticsearch.action.index.IndexResponse$Builder.build(IndexResponse.java:103) ~[elasticsearch-7.5.1.jar:7.5.1]
		at org.elasticsearch.action.index.IndexResponse.fromXContent(IndexResponse.java:85) ~[elasticsearch-7.5.1.jar:7.5.1]
		at org.codelibs.elasticsearch.client.action.HttpIndexAction.lambda$execute$0(HttpIndexAction.java:55) ~[elasticsearch-httpclient-7.5.0.jar:?]
		at org.codelibs.curl.CurlRequest.lambda$execute$4(CurlRequest.java:220) ~[curl4j-1.2.4.jar:?]
		at org.codelibs.curl.CurlRequest.lambda$connect$3(CurlRequest.java:199) ~[curl4j-1.2.4.jar:?]
		at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426) ~[?:?]
		at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290) ~[?:?]
		at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020) ~[?:?]
		at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656) ~[?:?]
		at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594) ~[?:?]
		at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177) ~[?:?]
	Suppressed: org.codelibs.elasticsearch.client.action.HttpAction$CurlResponseException: {"error":{"root_cause":[{"type":"version_conflict_engine_exception","reason":"[BZ6rkm8B66oCPuF_NyYw-1.aHR0cHM6Ly9zaG9wLmRlbGZvbmljcy5jb20v]: version conflict, document already exists (current version [1])","index_uuid":"d5U8n5z2SJy6rf2x4O2Trg","shard":"0","index":".crawler.queue"}],"type":"version_conflict_engine_exception","reason":"[BZ6rkm8B66oCPuF_NyYw-1.aHR0cHM6Ly9zaG9wLmRlbGZvbmljcy5jb20v]: version conflict, document already exists (current version [1])","index_uuid":"d5U8n5z2SJy6rf2x4O2Trg","shard":"0","index":".crawler.queue"},"status":409}
2020-01-11 22:03:24,047 [eshttp] DEBUG >>> PUT http://localhost:9201/.crawler.queue/_doc/BZ6rkm8B66oCPuF_NyYw-1.aHR0cHM6Ly9zaG9wLmRlbGZvbmljcy5jb20v?timeout=1m&refresh=true&op_type=create
2020-01-11 22:03:24,047 [eshttp] DEBUG >>> Content-Type=application/json
2020-01-11 22:03:24,047 [eshttp] DEBUG >>> {"sessionId":"BZ6rkm8B66oCPuF_NyYw-1","method":"GET","url":"https://shop.delfonics.com/","depth":0,"lastModified":0,"createTime":1578747784437}
2020-01-11 22:03:24,052 [eshttp] DEBUG <<< {"error":{"root_cause":[{"type":"version_conflict_engine_exception","reason":"[BZ6rkm8B66oCPuF_NyYw-1.aHR0cHM6Ly9zaG9wLmRlbGZvbmljcy5jb20v]: version conflict, document already exists (current version [1])","index_uuid":"d5U8n5z2SJy6rf2x4O2Trg","shard":"0","index":".crawler.queue"}],"type":"version_conflict_engine_exception","reason":"[BZ6rkm8B66oCPuF_NyYw-1.aHR0cHM6Ly9zaG9wLmRlbGZvbmljcy5jb20v]: version conflict, document already exists (current version [1])","index_uuid":"d5U8n5z2SJy6rf2x4O2Trg","shard":"0","index":".crawler.queue"},"status":409}   
```

Thanx.

**Comment by marevol** [comment]
If you have many target urls in crawling setting, retry accesses on errors takes time to start crawler.
It'll be improved in a next release.
